# Permalinks
permalink:        pretty

# Setup
title:            lexusalex.github.io
tagline:          'Pair is not a function'
paginate:         15
paginate_path:    "page:num"
highlighter:      rouge
future:           false
show_drafts:      false

url:              https://lexusalex.github.io
shorturl:         lexusalex.github.io

author:
  name:           Алексей Шмелев
  url:            lexusalex.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  О блоге: '/about'
  Книги: '/books'
  Архив записей: '/archive'
  Лента: '/atom.xml'

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-gist
