# Permalinks
permalink:        pretty
timezone: Europe/Moscow
language: ru

# Setup
title:            LexusAlex blog
tagline:          'Заметки web разработчика'
paginate:         10
version:          0.0.1
paginate_path:    "page:num"
highlighter:      rouge
future:           false
show_drafts:      false
description: >
  Заметки web разработчика

url:              http://lexusalex.ru
shorturl:         lexusalex.ru
baseurl:          ""

author:
  name:           Алексей Шмелев
  url:            lexusalex.ru

# This is the list of pages to include in the header of the website.
pages_list:
  О блоге: '/about'
  Книги: '/books'
  Архив записей: '/archive'
  Лента: '/atom.xml'

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-gist
