title:  "LexusAlex"
email:  alexsey_89@bk.ru
tagline: Заметки web разработчика

url:  https://lexusalex.ru
shorturl: lexusalex.ru
baseurl:  ""

author: Алексей Шмелев
permalink: pretty
timezone: Europe/Moscow
language: ru

paginate: 10
future: false
show_drafts:  false

markdown: kramdown
highlighter: false
plugins:
  - jekyll-feed
  - jekyll-paginate