@startuml

card group1 [
a
audio
button
canvas
details
dialog
embed
fieldset
figure
form
iframe
img
input
label
link
meta
meter
object
picture
progress
select
svg
textared
video
abbr
b
bdi
bdo
blockquote
cite
code
data
datalist
kbd
]


card group3 [
p
pre
q
ruby
s
samp
small
span
strong
sup
sub
time
u
var
ol
ul
noscript
output
script
table
template
text
hr
map
area
dl
wbr
br
del
dfn
em
i
mark
ins
]

@enduml