@startuml

actor client

rectangle HTTP
rectangle Console
rectangle Rabbitmq
rectangle Android
rectangle iOS

client  -->> HTTP : веб
client -->> Console
client -->> Rabbitmq
client -->> Android
client -->> iOS


@enduml